[server]
headless = true
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 10000

[client]
toolbarMode = "viewer"

[theme]
primaryColor = "#6366f1"
backgroundColor = "#070a12"
secondaryBackgroundColor = "#0c101d"
textColor = "#f1f5f9"
font = "sans serif"
